# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84920c12eede64bd9d7295d3779e6399d8aa70fe5b3718d8bf65d1ddf3b869e7b677aa8b5898ae2ec09de507720ba0a8189d1eb2709e7f77bfd711217ab6b2d3

test:
  secret_key_base: f5fe0458068a43a1f766e0fae4605e1d2a741e47b01b3c3b53fb4b1f19c4ac353e8366e5a8b2d2bbe617b9170149223355721d8a87526a802a56b58712f9c5d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
